// Aurora DermaPod RFQ Comments Database
// Edit this file directly in the codebase, or use the "Export Comments" button in the UI to download a new version.
const rfqSavedComments = {
  "overview-limit": "The objective is to develop an integrated 360° full-body dermatological imaging gantry capable of capturing high-resolution images of the entire patient for skin lesion and tumor assessment. The system is intended for deployment in primary care clinics, dermatology practices, and research environments, supporting standardized image acquisition, longitudinal lesion monitoring, and downstream AI-assisted analysis. The solution should prioritize complete body coverage, repeatable imaging, patient safety, efficient clinical workflow, and scalability for future commercial deployment.",
  "overview-poss": "Current imaging, robotics, illumination, synchronization, and computer vision technologies are capable of delivering a 360° dermatological imaging platform. Achieving the required clinical performance will require careful integration of high-resolution camera systems, precision positioning, calibrated illumination, accurate color management, robust calibration procedures, and software-controlled image acquisition. Longitudinal lesion tracking and AI classification are supported through consistent, repeatable image capture, while the AI algorithms themselves remain outside the scope of this subsystem.",
  "targets-limit": "NA",
  "targets-poss": "NA",
  "excluded-limit": "NA",
  "excluded-poss": "NA",
  "phase-limit": "NA",
  "phase-poss": "NA",
  "mec1-limit": "The specified patient envelope is appropriate for accommodating the majority (5th–95th percentile) of the adult population while maintaining a compact clinical footprint. The imaging system, camera arrangement, robotic workspace, and illumination geometry should be designed to provide complete body coverage within this envelope. Light handholds/grips should be incorporated to improve patient stability and pose repeatability during image acquisition without obstructing anatomical regions of interest. Provision may be made to accommodate larger-bodied patients by increasing the imaging envelope or adjusting the camera positions, provided the impact on image quality, system footprint, acquisition time, and overall performance is justified.",
  "mec1-poss": "Designing an imaging gantry for a 1.0 m × 0.6 m × 2.0 m patient envelope is achievable using commercially available camera systems, robotic positioning mechanisms, and illumination hardware. Integrating ergonomic handholds within the imaging volume is straightforward and can improve patient stability and imaging consistency. Support for larger-bodied patients can be accommodated through appropriate mechanical design modifications or an expanded imaging workspace, subject to validation of coverage, image quality, and system performance.",
  "mec2-limit": "The specified maximum system footprint is appropriate for installation in typical primary care and dermatology clinics where floor space is limited. The complete imaging gantry, including cameras, positioning mechanism, illumination, electronics, and safety features, should be integrated within a footprint not exceeding <strong>2.5 m × 2.5 m</strong> and an overall height of <strong>2.6 m</strong>. A compact design will improve installation flexibility, clinical workflow, transportation, and commercial viability while maintaining the required imaging performance and patient accessibility. Any increase in footprint should be supported by clear technical justification and demonstrable benefits.",
  "mec2-poss": "<strong>Feasible.</strong> The specified footprint and height are achievable using modern compact mechanical structures, integrated camera assemblies, and efficient cable and electronics management. Careful system layout and optimization of the camera arrangement and positioning mechanism can satisfy the dimensional constraints without compromising patient access, imaging coverage, or serviceability. Footprint minimization should remain a key design consideration throughout the mechanical and system integration process.",
  "img13-limit": "The imaging subsystem shall provide <strong>at least 98% body-surface coverage</strong> for a standard anthropomorphic phantom representing the <strong>5th–95th percentile adult population</strong>. Coverage shall be demonstrated through a documented validation study that identifies all imaged and non-imaged regions. The proposed camera configuration, field of view, imaging poses, and patient positioning strategy should collectively minimize occluded areas while maintaining the required image quality and patient cycle time. Small anatomically challenging regions (e.g., skin folds or areas naturally occluded in a standing pose) should be identified and justified within the coverage analysis.",
  "img13-poss": "<strong>Feasible.</strong> Achieving ≥98% body-surface coverage is technically achievable through an optimized combination of camera placement, imaging geometry, and patient positioning, supplemented by appropriate robotic motion or multiple acquisition poses where required. Coverage can be quantitatively verified using anthropomorphic phantoms and documented through a coverage-validation report, ensuring compliance with the specified performance requirement.",
  "img1-limit": "The final camera count is highly dependent on the selected system architecture and should be determined through a system-level trade-off study. Factors influencing the required number of cameras include the positioning mechanism (static or moving cameras), patient repositioning strategy, required body-surface coverage (≥98%), field of view, working distance, target pixel density, image overlap, capture time, and overall image quality. A moving-camera architecture may reduce the number of cameras at the expense of increased mechanical complexity and acquisition time, whereas a fixed-camera architecture may require additional cameras to achieve the required coverage without patient repositioning. Furthermore, increasing the imaging field of view while maintaining the required spatial resolution may necessitate higher-resolution sensors or additional cameras, both of which can increase the overall system BOM cost. The proposed camera count should therefore represent an optimized balance between coverage, performance, cycle time, complexity, and cost.",
  "img1-poss": "The optimum camera count should be established during the system architecture phase through coverage simulation and optical analysis. Multiple architectural approaches (e.g., fixed multi-camera arrays, robotic/moving cameras, or hybrid systems) are capable of meeting the performance requirements. The selected solution should demonstrate compliance with body-surface coverage, patient cycle time, image quality, and production BOM targets while minimizing system complexity and lifecycle costs.",
  "img2-limit": "The final sensor selection should be based on system-level trade-offs including required pixel density, field of view, working distance, optics, acquisition speed, and overall system cost. While a <strong>50 MP-class CMOS sensor</strong> is a suitable baseline, higher-resolution sensors may reduce the required camera count for larger fields of view, whereas lower-resolution sensors may require additional cameras or imaging poses. The final sensor choice should be optimized alongside the overall system architecture to balance image quality, coverage, cycle time, and BOM cost.",
  "img2-poss": "Commercial CMOS sensors in the <strong>50 MP to 100 MP</strong> range are readily available and can meet the imaging requirements when combined with appropriate optics. Final sensor selection should be validated through optical, coverage, and cost-performance trade-off analysis.",
  "img3-limit": "Achieving an effective pixel pitch of <strong>≤30 µm/pixel across the entire body surface and working volume</strong> is a challenging system-level requirement. Maintaining a uniform pixel density over the full body while preserving complete coverage typically requires a reduced field of view, additional cameras, higher-resolution sensors, or robotic repositioning, all of which increase system complexity and BOM cost. If robotic motion or multiple imaging positions are used, factors such as patient motion, motion artefacts, repeatability, and increased acquisition time must also be considered. Furthermore, reducing the field of view to increase pixel density can reduce the achievable depth of field, requiring additional optical optimization. The RFQ also does not clearly define the ROI workflow or specify how the high-resolution ROI is selected (e.g., clinician-selected, AI-assisted, or predefined), and further clarification would be beneficial.",
  "img3-poss": "The requirement can be achieved through an optimized combination of sensor resolution, optics, camera configuration, and imaging architecture. However, maintaining <strong>≤30 µm/pixel across the entire body envelope</strong> without tolerance is challenging and may require additional cameras, higher-resolution sensors, reduced fields of view, or robotic imaging approaches, increasing system complexity and BOM cost. Reducing the field of view to maintain pixel density also decreases the achievable depth of field, potentially requiring alternative approaches such as optimized optics, autofocus, or focus stacking. A practical implementation may therefore require an acceptable tolerance in pixel density over the full imaging envelope or specifying <strong>30 px/mm as a maximum target</strong> while allowing controlled variation with working distance. The final solution should be determined through a system-level optimization balancing image quality, coverage, depth of field, acquisition time, camera count, and overall cost.",
  "img4-limit": "The requirement for <strong>≥12-bit per channel</strong> image acquisition with simultaneous <strong>linear RAW</strong> and <strong>processed/compressed</strong> image output is appropriate for preserving image quality and supporting both clinical review and downstream image processing. Linear RAW data enables calibration, color correction, and future algorithm development, while processed images support routine clinical workflows.",
  "img4-poss": "Commercial imaging sensors and camera interfaces commonly support <strong>12-bit or higher</strong> RAW output together with processed image formats (e.g., JPEG/TIFF). The requirement can be implemented using standard imaging pipelines with appropriate processing.",
  "img5-limit": "The lens selection should be optimized to achieve the required image quality while maintaining <strong>low distortion (≤1.5% TV distortion)</strong>, minimal chromatic aberration, and consistent sharpness across the full field of view. The choice between fixed focus, motorized focus, liquid lens, or focus stacking should be based on the required depth of field, acquisition time, and imaging architecture. If motorized focus or a liquid lens is adopted, the impact of focus-dependent optical variations, including distortion, chromatic aberration, and magnification changes, should be evaluated. Where significant, calibration should be performed for each focus position to maintain imaging accuracy. The feasibility of these approaches should be assessed during the optical design phase.",
  "img5-poss": "Commercial low-distortion, color-corrected lenses are available to meet the optical requirements. The optimal focusing approach should be determined through an optical trade-off study evaluating fixed focus, motorized focus, liquid lenses, and focus stacking with respect to depth of field, image quality, acquisition time, system complexity, and cost. Lens characterization should include distortion measurement (e.g., checkerboard calibration), chromatic aberration assessment (e.g., RGB channel shift across the field and focus positions), sharpness/MTF evaluation, and repeatability testing. If motorized focus or liquid lenses are adopted, focus-dependent optical effects—including distortion, chromatic aberration, magnification, and focus shift—should be quantified, and calibration models should be generated for each focus position where necessary to maintain consistent imaging performance.",
  "img6-limit": "The working distance should be optimized to achieve the required patient envelope, pixel density, depth of field, image quality, and system footprint. It also influences the field of view, camera count, lens selection, and illumination design, and should therefore be determined through system-level optimization.",
  "img6-poss": "The optimum working distance can be determined through optical modelling and trade-off analysis, balancing coverage, pixel density, depth of field, camera count, image quality, and BOM cost. Final validation should be performed through simulation and prototype testing.",
  "img7-limit": "This DOF requirement is incomplete, as the <strong>Circle of Confusion (CoC) is not specified</strong>. DOF depends on the acceptable CoC criterion; therefore, the CoC (or equivalent image sharpness criterion, e.g., MTF/resolution threshold) should be defined to make this requirement measurable and verifiable.",
  "img7-poss": "<strong>Conditionally feasible.</strong> The requirement is achievable; however, the acceptable <strong>Circle of Confusion (CoC)</strong> or equivalent image sharpness criterion should be defined before the optical system can be designed and validated. The optimum approach—fixed focus, motorized focus, liquid lens, or focus stacking—should be evaluated based on the required depth of field, image quality, acquisition time, system complexity, and cost. If variable-focus methods are adopted, focus-dependent calibration may be required to maintain consistent imaging performance.",
  "img8-limit": "The specified color accuracy targets are appropriate for dermatological imaging. Achieving consistent performance across <strong>Fitzpatrick skin types I–VI</strong> requires careful optimization of illumination, sensor spectral response, optics, white balance, and color calibration. The calibration methodology, lighting conditions, and evaluation procedure should be clearly defined to ensure repeatable and verifiable results.",
  "img8-poss": "The requirement can be achieved using high-CRI calibrated illumination, RAW image capture, ColorChecker-based profiling, camera characterization, and color calibration (e.g., CCM/3D LUT). Performance should be validated across all Fitzpatrick skin types under standardized imaging conditions.",
  "img9-limit": "The system should support both <strong>cross-polarized</strong> and <strong>non-polarized</strong> imaging to enhance visualization of subsurface structures and surface features, respectively. The polarization switching mechanism (e.g., electronic or mechanical) should be selected to minimize switching time while maintaining consistent illumination, alignment, and image quality.",
  "img9-poss": "<strong>Feasible.</strong> Commercial polarization components and illumination systems can support rapid switching between imaging modes within a single patient cycle. The selected implementation should be validated for switching speed, repeatability, polarization efficiency, and long-term reliability.",
  "img10-limit": "Maintaining an <strong>inter-camera color consistency of ΔE₀₀ ≤ 1.5</strong> is important to ensure seamless appearance and reliable comparison between images acquired from different cameras. This requires consistent illumination, sensor characterization, lens matching, and camera-specific color calibration across all imaging units.",
  "img10-poss": "The requirement can be achieved through camera-to-camera calibration using standardized color targets (e.g., X-Rite ColorChecker), sensor characterization, white balance calibration, and camera-specific CCM/3D LUT generation. Periodic recalibration should be performed to maintain long-term color consistency across all cameras.",
  "img11-limit": "OK",
  "img11-poss": "OK",
  "img12-limit": "OK",
  "img12-poss": "OK",
  "rob1-limit": "NA",
  "rob1-poss": "NA",
  "rob2-limit": "NA",
  "rob2-poss": "Precision drives with optical encoders ensure repeatability to within specification.",
  "rob3-limit": "NA",
  "rob3-poss": "Extrinsic calibration matrix corrects structural offsets.",
  "rob4-limit": "NA",
  "rob4-poss": "360 degree rotation coupled with vertical camera stack covers entire torso and limbs in a single run.",
  "rob6-limit": "NA",
  "rob6-poss": "Safe-torque-off drives, protective bumpers, and area laser scanners prevent patient collision.",
  "rob7-limit": "NA",
  "rob7-poss": "Dual-channel e-stop switches cut drive power via safety relays.",
  "rob8-limit": "NA",
  "rob8-poss": "Quiet motor controllers and rubber-damped belt drives maintain operational noise below 45 dBA.",
  "rob9-limit": "NA",
  "rob9-poss": "Spring-applied electromagnetic brakes lock column rotation and vertical stages on power loss.",
  "rob10-limit": "NA",
  "rob10-poss": "Depth sensor arrays verify posture and centering prior to sweep, alerting operator of misalignments.",
  "ill1-limit": "NA",
  "ill1-poss": "Customized high-CRI LED strobe modules utilize high-performance emitters matching the 5700K baseline.",
  "ill2-limit": "NA",
  "ill2-poss": "Custom diffuser optics guarantee light uniformity across the patient envelope.",
  "ill3-limit": "NA",
  "ill3-poss": "Precision-mounted linear polarization films are utilized, achieving high extinction ratios.",
  "ill4-limit": "NA",
  "ill4-poss": "Strobe duration and intensity are designed to comply with eye-safe Risk Group 1 limits.",
  "ill5-limit": "NA",
  "ill5-poss": "NA",
  "ill6-limit": "NA",
  "ill6-poss": "Feasible. High-power strobe drivers with high-speed current regulators can be customized to support the required flash frequency and synchronization.",
  "rob5-limit": "NA",
  "rob5-poss": "NA",
  "syn1-limit": "NA",
  "syn1-poss": "NA",
  "syn2-limit": "NA",
  "syn2-poss": "NA",
  "syn3-limit": "NA",
  "syn3-poss": "NA",
  "syn4-limit": "NA",
  "syn4-poss": "NA",
  "syn5-limit": "NA",
  "syn5-poss": "NA",
  "cal1-limit": "NA",
  "cal1-poss": "Chessboard-based calibration algorithms yield extrinsic calibration errors well within specifications.",
  "cal2-limit": "NA",
  "cal2-poss": "Flat-field calibration targets and sensor gain maps correct pixel-to-pixel sensitivity differences.",
  "cal3-limit": "NA",
  "cal3-poss": "Profiling matches camera outputs to standardized target profiles.",
  "cal4-limit": "NA",
  "cal4-poss": "Automated test routine calibrates and validates skin-tone compliance.",
  "cal5-limit": "NA",
  "cal5-poss": "Quick-check validation algorithm verifies target calibration metrics on startup.",
  "calgeneral-limit": "NA",
  "calgeneral-poss": "Automated software routine guides the operator through calibration target placement step-by-step.",
  "syn6-limit": "NA",
  "syn6-poss": "NA",
  "syn7-limit": "NA",
  "syn7-poss": "NA",
  "cyber1-limit": "NA",
  "cyber1-poss": "NA",
  "cyber2-limit": "NA",
  "cyber2-poss": "NA",
  "posesched-limit": "NA",
  "posesched-poss": "NA",
  "life1-limit": "NA",
  "life1-poss": "NA",
  "life2-limit": "NA",
  "life2-poss": "NA",
  "life3-limit": "NA",
  "life3-poss": "NA",
  "transfer-limit": "NA",
  "transfer-poss": "NA",
  "fda-limit": "NA",
  "fda-poss": "NA",
  "iec60601-1-limit": "NA",
  "iec60601-1-poss": "NA",
  "iec60601-1-2-limit": "NA",
  "iec60601-1-2-poss": "NA",
  "iec62304-limit": "NA",
  "iec62304-poss": "NA",
  "iso14971-limit": "NA",
  "iso14971-poss": "NA",
  "iec62366-limit": "NA",
  "iec62366-poss": "NA",
  "clean-limit": "NA",
  "clean-poss": "NA",
  "cost-limit": "NA",
  "cost-poss": "NA",
  "warranty-limit": "NA",
  "warranty-poss": "NA",
  "deliv-limit": "NA",
  "deliv-poss": "NA"
};
